Update dependencies

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -12,14 +12,14 @@ if [ ! -x $PHP_CS_FIXER ]; then
     exit 1
 fi
 
-if [ ! -x $PSALM ]; then
-    echo ""
-    echo "vimeo/psalm not found. Try:"
-    echo ""
-    echo "  composer install"
-    echo ""
-    exit 1
-fi
+#if [ ! -x $PSALM ]; then
+#    echo ""
+#    echo "vimeo/psalm not found. Try:"
+#    echo ""
+#    echo "  composer install"
+#    echo ""
+#    exit 1
+#fi
 
 FILES=`git status --porcelain | grep -E '^[AM] +(src|tests).*\.php$' | cut -c 4- | tr '\n' ' '`
 if [ -z "$FILES" ]; then
